name: Cyclomatic Complexity

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gocyclo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Install gocyclo
        run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

      - name: Run make gocyclo
        run: make gocyclo
