name: Code Duplication

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  dupl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version: "1.22"
          cache: true

      - name: Run make dupl
        run: make dupl
