name: Examples

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  examples:
    name: Build examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: examples/01-hello-natsql/go.mod
      - name: Build all examples
        run: make examples
