name: Lint

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
          make lint
